name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL='mysql://p8htyjzhmbwyb89vfl6y:pscale_pw_VYxERgJDvKAe8pVH4xokcd7LV20uYzhtD5OBS6f2qC8@aws.connect.psdb.cloud/chirpdb?sslaccept=strict'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript type checking
      run: npx tsc --noEmit

    - name: Run Lint
      run: npm run lint
